### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by adrianbsb** [michaeldegroot/DoctrineEncryptBundle#10]
When I tried to run `./app/console doctrine:decrypt:database` I got this

```
In DoctrineDecryptDatabaseCommand.php line 43:
Access to undeclared static property: Ambta\DoctrineEncryptBundle\DependencyInjection\DoctrineEncryptExtension::$supportedEncryptorClasses 
```

**Comment by Patryk27** [comment]
Same here - seems it should say `DoctrineEncryptExtension::SupportedEncryptorClasses` instead of `DoctrineEncryptExtension::$supportedEncryptorClasses` inside the `DoctrineDecryptDatabaseCommand::execute` method.

**Comment by dbu** [comment]
this has been fixed in https://github.com/michaeldegroot/DoctrineEncryptBundle/commit/d9a6d7f6b4ed705c2240373256cb513ed3f360f3 but unfortunately no release has been tagged since that has been merged. 

@michaeldegroot any chance to get a new version of this bundle?

**Comment by michaeldegroot** [comment]
Sure I could publish a new release. But I can't test it at the moment. It would be nice if there could be a integration with travis for unit testing

**Comment by dbu** [comment]
i'll see what i can do

**Comment by michaeldegroot** [comment]
@dbu maybe we can use docker? it would be interesting to get this setup going somehow, I have continuous integration in my npm packages as well and it works really well for open source projects
