### ISSUE TITLE
console commands not working

### ISSUE THREAD

**Issue by D4rkPh0en1x** [michaeldegroot/DoctrineEncryptBundle#12]
Hi
I wanted to try a decrypt/encrypt over the console but none of the commands exists under Symfony 4
Is that a normal behaviour?

**Comment by michaeldegroot** [comment]
please re-open if it's still a issue

**Comment by coudenysj** [comment]
It looks like this is still an issue...

**Comment by coudenysj** [comment]
Sorry, the 4.0.3 works :).
