### ISSUE TITLE
Upgrading from v3.0.3 to v4.0.1

### ISSUE THREAD

**Issue by Herz3h** [michaeldegroot/DoctrineEncryptBundle#14]
I'm trying to update the bundle to latest version, since I'm having weird issues (sometimes password decryption takes longer than 30seconds and make the server not respond, or right now using form_widget(form.smtpPassword) has weird behavior where is includes another twig file.....I have no idea why). 

The problem is it says halite v4.5.1 requires php 7.2 and I'm using php 7.1...Is there a way to use php7.1 ? 

I have tried v4.0.0 but, it has the constructor not matching the interface.

**Comment by dbu** [comment]
halite uses libsodium, and libsodium is only available in php 7.2
