### ISSUE TITLE
Support for Symfony 4

### ISSUE THREAD

**Issue by mattwood1** [michaeldegroot/DoctrineEncryptBundle#15]
I've tried to get this working on a symfony 4 project and it doesn't register the bundle, The commands are not available. I have managed to get other symfony 3 bundles to work in symfony 4, but with this one, its just not working.

Any help or assistance would be welcomed. If there are similar bundles that do work in symfony 4 I'd be interested to know, but after spending a while searching Google, nothing really seems to be developed for symfony 4 and data encryption.

**Comment by mattwood1** [comment]
Seems like a dead project.

**Comment by mvaljento** [comment]
Any chance of Symfony 4 version coming out?

**Comment by michaeldegroot** [comment]
The project is not dead, it has been gaining more traction lately. We are busy with adding unit testing and then we will try to fix issues

**Comment by scasei** [comment]
Hi, it works for me on a symfony 4 project, but I have a really strange bug:
Value is correct decrypted but its not unwrapped of HiddenString correctly. My workaround is to unwrap it manually in the getter of the object attribute. 

Im using it out of the box with Halite.

**Comment by cdesign** [comment]
I got this to work on Symfony 4.3 with the following:

1) `composer require michaeldegroot/doctrine-encrypt-bundle`

2) Add this line to the array defined in /config/bundles.php:

     `Ambta\DoctrineEncryptBundle\AmbtaDoctrineEncryptBundle::class => ['all' => true],`

3) Create the config file:

     `config/packages/ambta_doctrine_encrypt.yaml`

     and add this to it:

```
ambta_doctrine_encrypt:
    encryptor_class: Halite # or Defuse
    secret_directory_path: '%kernel.project_dir%'
```

4) `php bin/console cache:clear` just to be safe

5) Then as docs state, add the `@Encrypted()` annotation to each property in your entity class that you want to encrypt:

```
    /**
     * @ORM\Column(type="text", nullable=true)
     * @Encrypted()
     */
    private $comment;
```

After an entity is persisted, the target field will contain encrypted data, something like this:

```
MUIEAO_g3d8wGWEGksntbQcyW3sWS3xy5d20yMWB5-LxopC8uNmv9lPjtSYeNW2M2Zk-66c0es5K_nYNP7UOKNkv99N0tBmjMobIY8ELHQk_r4NnlzFeeR4k3Uuxd1SRTSx_xsBCbmplGaLi36q9XJ_Qmxre6aqU04SeKCaXEwYLBHBFwqquo4I=<ENC>
```

I have not tested thoroughly, but did notice that it only seems to work with columns of type 'text.' Please let me know if I'm wrong about that.. I need something that will also encrypt int data.

**Comment by michaeldegroot** [comment]
if problems presist. please reopen
