### ISSUE TITLE
Encryption and search queries

### ISSUE THREAD

**Issue by soulghard** [michaeldegroot/DoctrineEncryptBundle#16]
Hello,

I'm using your bundle to encrypt last names in my database. When I want to retireve some people based on a Doctrine query search like give me people with last names starts with "Che" there is no result. 

Is there any way to make queries on encrypted fields ?

**Comment by sstok** [comment]
https://paragonie.com/blog/2017/05/building-searchable-encrypted-databases-with-php-and-sql maybe this can help you 👍

**Comment by michaeldegroot** [comment]
could be a nice feature but I don't see it being added any time soon, not from me anyway
