### ISSUE TITLE
Update Configuration for Symfony 4.3 and next

### ISSUE THREAD

**Issue by rcournault** [michaeldegroot/DoctrineEncryptBundle#23]
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "ambta_doctrine_encrypt" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.
 .......vendor/michaeldegroot/doctrine-encrypt-bundle/Ambta/DoctrineEncryptBundle/DependencyInjection/Configuration.php:26 

Il's possible to merge this pull ? 
https://github.com/michaeldegroot/DoctrineEncryptBundle/pull/21

**Comment by develth** [comment]
+1 !

After that change i was able to use it in symfony 5

**Comment by nicolashachet** [comment]
+1 :)

**Comment by syfim** [comment]
+

**Comment by michaeldegroot** [comment]
fixed in 12cb3ffd5b53bb6099e99c922d75499cc0c05213
