### ISSUE TITLE
Entity always updated 

### ISSUE THREAD

**Issue by benpic87** [michaeldegroot/DoctrineEncryptBundle#25]
Is there a reason why every encrypted property are updated all the time  even if the value did not change? This causes a lot of traffic on my database server and sometimes causes deadlocks. Updated only the changed properties would fix this (I guess).

Thank you,

**Comment by arrabal-hidalgo** [comment]
First of all, English is not my native language, yet I hope to explain myself well.

For the same plain text, the encrypted value always varies. Causing the entity manager to consider that the value of these fields has varied and therefore the entity must be updated to reflect that changes(even if the plain text is the same)

I have done a workaround, using a preFlush event listener, checking if the original fields and the current value, both decrypted, really differ and otherwise reversing those changes.

**Comment by benpic87** [comment]
> First of all, English is not my native language, yet I hope to explain myself well.
> 
> For the same plain text, the encrypted value always varies. Causing the entity manager to consider that the value of these fields has varied and therefore the entity must be updated to reflect that changes(even if the plain text is the same)
> 
> I have done a workaround, using a preFlush event listener, checking if the original fields and the current value, both decrypted, really differ and otherwise reversing those changes. In order to avoid unnecessary updates.

Could you post the code of your preFlush event listener?

Thank you,

**Comment by michaeldegroot** [comment]
@arrabal-hidalgo yes please post the code, I will merge it so it's useful for everyone!

**Comment by alejandro-arrabal** [comment]
Sorry for the delay, I was busy those days, there is my workaround:
`

    /**
     * On preFlush revert encrypt "fakes" changes caused because every time we encrypt our encrypted field differs from original
     * even if the plain value it's the same.
     * @param PreFlushEventArgs $args
     */
    public function preFlush(PreFlushEventArgs $args)
    {
        $em = $args->getEntityManager();
        $uow = $em->getUnitOfWork();
        $identityMap = $uow->getIdentityMap();
        if (!isset($identityMap[<MY_CLASS_WITH_ENCRYPTED_FIELDS>::class])) {
            return;
        }
        foreach ($identityMap[<MY_CLASS_WITH_ENCRYPTED_FIELDS>::class] as $entity) {
            $uow->scheduleForUpdate($entity);
            $originalSet = $uow->getOriginalEntityData($entity);
            if (!$this->hasEncryptedFieldsChanged($originalSet, $entity)) {
                $entity = $this->revertEncryptedFields($entity, $originalSet);
            } else {
                //Some other operations when plain values really changes
            }
            $uow->computeChangeSet($em->getClassMetadata(<MY_CLASS_WITH_ENCRYPTED_FIELDS>::class), $entity);
        }
    }
`




    /**
     * Method that check if current encrypt values match with old ones
     * @param array $originalData
     * @param $entity
     * @return bool
     */
    private function hasEncryptedFieldsChanged($originalData, $entity)
    {
        // substr is needed because DoctrineEncryptBundle add <ENC> at the end of the encryted values
        $oldEmail = $this->encryptor->decrypt(substr($originalData['email'], 0, -5));
        // I don't remember if the get function returns the plain value or the encryted one if the plain value is returned
        // the decrypt step must be skipped
        $newEmail = $this->encryptor->decrypt(substr($entity->getEmail(), 0, -5));
        //other fields can be checked as well
        return $newEmail != $oldEmail;
    }

**Comment by jriboux** [comment]
@benpic87 I think I found a workaround using the "deferred explicit" tracking policy [(See doctrine documentation)](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/change-tracking-policies.html#deferred-explicit).

Setting deffered explicit tracking policy to all entities containing encrypted fields will prevent them from being automatically persisted on flush. They will be persisted only if persist() is explicitely called on each instance you want to save in DB.

**Comment by benpic87** [comment]
@jriboux I'm aware of this possibility, but a persisted encrypted field will be updated even if it is the same. So it's an option that improve performance but doesn't fix this issue.

**Comment by benpic87** [comment]
using @alejandro-arrabal code, I end up with this. I haven't tested really tested iit fully, but it seems to work. However, I'm not a doctrine expert can someone review this:
`<?php

namespace AppBundle\Listener\Core;

use Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface;
use Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber;
use Doctrine\Common\Annotations\Reader;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Event\PreFlushEventArgs;
use Doctrine\ORM\UnitOfWork;
use ParagonIE\Halite\Alerts\HaliteAlert;
use ParagonIE\Halite\HiddenString;
use ReflectionClass;
use ReflectionException;
use ReflectionProperty;
use Symfony\Component\PropertyAccess\PropertyAccess;


class EncryptBundlePreFlushEventListener
{

    /**
     * @var Reader
     */
    private $annReader;

    /**
     * @var EncryptorInterface
     */
    private $encryptor;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var UnitOfWork
     */
    private $uow;

    /**
     * Initialization of subscriber
     *
     * @param Reader $annReader
     * @param EncryptorInterface $encryptor
     * @param EntityManagerInterface $em
     */
    public function __construct(Reader $annReader, EncryptorInterface $encryptor, EntityManagerInterface $em)
    {
        $this->annReader = $annReader;
        $this->encryptor = $encryptor;
        $this->em = $em;
    }


    /**
     * On preFlush revert encrypt "fakes" changes caused because every time we encrypt our encrypted field differs from original
     * even if the plain value it's the same.
     * @param PreFlushEventArgs $args
     * @throws ReflectionException
     */
    public function preFlush(PreFlushEventArgs $args)
    {
        $this->em = $args->getEntityManager();
        $this->uow = $this->em->getUnitOfWork();
        $identityMap = $this->uow->getIdentityMap();


        foreach ( $identityMap as $entityMap) {
            foreach ($entityMap as $entity) {

                if ($this->uow->isScheduledForInsert($entity) || $this->uow->isScheduledForDelete($entity)) {
                    return;
                }
                $this->revertEncryptionIfNeeded($entity);
            }
        }
    }

    /**
     * @param $entity
     * @throws ReflectionException
     */
    private function revertEncryptionIfNeeded($entity){


        // Get the real class, we don't want to use the proxy classes
        if (strstr(get_class($entity), 'Proxies')) {
            $realClass = $this->em->getClassMetadata(get_class($entity))->getName();
        } else {
            $realClass = get_class($entity);
        }

        // Get ReflectionClass of our entity
        $properties = $this->getClassProperties($realClass);
        $pac = PropertyAccess::createPropertyAccessor();

        // Foreach property in the reflection class
        foreach ($properties as $refProperty) {
            if ($this->annReader->getPropertyAnnotation($refProperty, DoctrineEncryptSubscriber::ENCRYPTED_ANN_NAME)) {

                $originalSet = $this->uow->getOriginalEntityData($entity);

                //Check if original unencrypted differ from new unencrypted value
                if (!$this->hasEncryptedFieldsChanged($originalSet, $entity,$refProperty)) {
                    //Revert to original encrypted value if both unencrypted value are the same
                    $pac->setValue($entity,$refProperty->getName(),$originalSet[$refProperty->getName()]);
                }
            }
        }
    }


    /**
     * Method that check if current encrypt values match with old ones
     * @param array $originalData
     * @param $entity
     * @param ReflectionProperty $refProperty
     * @return bool
     */
    private function hasEncryptedFieldsChanged($originalData, $entity, ReflectionProperty $refProperty)
    {

        //Get old value
        try{
            if(!isset($originalData[$refProperty->getName()]))return true;

            $oldValue = $this->encryptor->decrypt(substr($originalData[$refProperty->getName()], 0, -5));
            if($oldValue instanceof HiddenString){
                $oldValue=$oldValue->getString();
            }
        }catch (HaliteAlert $e){
            $oldValue=$originalData[$refProperty->getName()];
        }

        //Get new value
        $pac = PropertyAccess::createPropertyAccessor();
        $newEntityValue = $pac->getValue($entity, $refProperty->getName());

        try{
            $newValue = $this->encryptor->decrypt(substr($newEntityValue, 0, -5));
        }catch (HaliteAlert $e){
            $newValue=$newEntityValue;
        }
        
        return $newValue != $oldValue;
    }

    /**
     * @param $className
     * @return array
     * @throws ReflectionException
     */
    private function getClassProperties($className)
    {
        $reflectionClass = new ReflectionClass($className);
        $properties      = $reflectionClass->getProperties();
        $propertiesArray = array();

        foreach ($properties as $property) {
            $propertyName = $property->getName();
            $propertiesArray[$propertyName] = $property;
        }

        if ($parentClass = $reflectionClass->getParentClass()) {
            $parentPropertiesArray = $this->getClassProperties($parentClass->getName());
            if (count($parentPropertiesArray) > 0) {
                $propertiesArray = array_merge($parentPropertiesArray, $propertiesArray);
            }
        }

        return $propertiesArray;
    }

}

`

**Comment by Zombaya** [comment]
There is an existing issue in the original project: [#24 Encrypted fields are constantly being persisted to the Database even when they aren't being modified](https://github.com/ambta/DoctrineEncryptBundle/issues/24).  That issue is still open but there seems to be some action at the moment there as well.

**Comment by michaeldegroot** [comment]
Should be fixed since commit 2c9b95db7d1949ec6afa92fd3452a7e185d25768 and since version 4.0.4
