### ISSUE TITLE
Can you add support to Symfony 5?

### ISSUE THREAD

**Issue by jaszfalvitamas** [michaeldegroot/DoctrineEncryptBundle#27]
Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /
  vendor/michaeldegroot/doctrine-encrypt-bundle/Ambta/DoctrineEncryptBundle/Dependenc
  yInjection/Configuration.php on line 25 and at least 1 expected

I cannot install the latest version (4.0.3), because my symfony/yaml doest not satisfy the 4.x constraint, currently is at 5.x.

**Comment by jaszfalvitamas** [comment]
Maybe just the packagist requirements have to be updated?

**Comment by michaeldegroot** [comment]
fixed in 9af25c4e9ea3c0b615a9c0b431608d6653d36144 release will be soon
